### ISSUE TITLE
Unable to create PR

### ISSUE THREAD

**Issue by ChrisTheBaron** [hybridgroup/cylon-site#102]
Hey,

I might just be following your documentation wrong, but I am unable to create a pull request. I'm trying to add a link to a module I've made [here](https://github.com/ChrisTheBaron/cylon-wemo) for the Belkin WeMo.

I've cloned the repo locally, checked out a branch called `wemo` and made the changes to the relevant files but when I try to push to `origin wemo`, I do not have permission to do so.

Am I doing something completely wrong here?

Cheers, Chris

**Comment by deadprogram** [comment]
Hi, @ChrisTheBaron I think the instructs are indeed a little confusing for this repo. Please just submit a pull request from your fork/branch against this fork's master branch.
