### ISSUE TITLE
Error in Guides -> Working With Robots

### ISSUE THREAD

**Issue by brutalchrist** [hybridgroup/cylon-site#109]
Hi everyone,

In the section `Guides -> Working With Robots` exists an error with the examples of Number#toScale. 

(0.5).**fromScale**(0, 200); // 100
(10).**fromScale**(0, 50);   // 50
(-1).**fromScale**(0, 50);   // 0

Cheers.
🌳

**Comment by deadprogram** [comment]
Hi, @brutalchrist thanks for pointing that out. Care to submit a PR with the fix? :)

**Comment by brutalchrist** [comment]
https://github.com/hybridgroup/cylon-site/pull/110 :-)

**Comment by deadprogram** [comment]
This was merged a while ago, but I forgot to close.

**Comment by brutalchrist** [comment]
Sorry @deadprogram :)
