### ISSUE TITLE
Website crashes in Chrome on Mac

### ISSUE THREAD

**Issue by bluepuma77** [hybridgroup/cylon-site#112]
When I leave the website https://cylonjs.com/ open for a few hours, the website crashes in latest Chrome browser on Mac with latest OS X. I usually have tens of tabs open for weeks, cyclonjs is the only one that crashes. 

I looked briefly into it, the website has an unusual high memory and CPU usage.

After 5 minutes (Task, Memory, CPU)
![bildschirmfoto 2016-02-02 um 16 24 59](https://cloud.githubusercontent.com/assets/5221187/12754083/23fe3d66-c9ca-11e5-86a1-fcdcdbfbce08.png)

5 minutes later (Task, Memory, CPU)
![bildschirmfoto 2016-02-02 um 16 29 01](https://cloud.githubusercontent.com/assets/5221187/12754092/2ebf794a-c9ca-11e5-9a7f-b9c58998b679.png)

Seems some Javascript library is going wild.

**Comment by deadprogram** [comment]
Hi, @bluepuma77 thanks for reporting this. We just merged https://github.com/hybridgroup/cylon-site/pull/113 which should address your issue.

**Comment by deadprogram** [comment]
Since this issue was resolved, I am going to close it. Please re-open if needed, thanks.
