### ISSUE TITLE
Note global installation to use command line tool

### ISSUE THREAD

**Issue by gunthercox** [hybridgroup/cylon-site#98]
On [line 19](https://github.com/hybridgroup/cylon-site/blob/7daad437120806b5038c620d99e7a5eb85efedf3/source/documentation/adding-new-hardware-support.html.haml#L19) of the [Adding New Hardware Support](http://cylonjs.com/documentation/adding-new-hardware-support/) page it says to install the cylon-cli tool using the command `npm install cylon-cli`.

I'm currently in the process of writing a custom driver and this command didn't work for me at first. I found that I had to use `npm install -g cylon-cli` to install it globally. I realize this is a really minor change, but I'm a new to node and I hope that noting this in the documentation might help someone else in the future.

**Comment by deadprogram** [comment]
Thanks for pointing this out, @gunthercox just pushed an update in commit https://github.com/hybridgroup/cylon-site/commit/e4059f254e928652920bc5d7b5d3d8f63c1b4a89

**Comment by edgarsilva** [comment]
This has been fixed and deployed, closing this issue.

Thanks for the heads up @gunthercox !
